# @package _global_
name: sac

buffer_size: 1000000
n_steps: 1000000
batch_size: 256

rl:
  gamma: 0.99
  tau: 0.005
  learning_rate: 3e-4
  ent_coef: auto

evaluation:
  evaluate_episodes: 5
  eval_interval: 5000

warmup:
  warmup_steps: 25000
