defaults:
  - algorithm: erl
  - _self_

seed: 42
device: auto
debug: false

env:
  id: FetchPickAndPlaceDense-v4
eval_env:
  id: FetchPickAndPlaceDense-v4

wandb:
  enabled: true
  project: evo_rl_surrogate_uncertainty_prediction
  entity: evo_rl
  name: null
  tags: []
